Adapt data model and add book service
PickwickSoft/libraary pull request #27
Opened 2022-11-18 18:44 UTC by garlontas

Closes #9

2022-11-18 20:04 UTC, ngarlonta requested changes
Fix iss

2022-11-18 20:04 UTC, ngarlonta commented on src/main/java/org/pickwicksoft/libraary/web/rest/AuthorResource.java
> +    public ResponseEntity<Author> addAuthorToBook(@PathVariable Long bookId, @RequestBody Author authorRequest) {
is this method needed?

2022-11-18 20:04 UTC, ngarlonta commented on src/main/java/org/pickwicksoft/libraary/web/rest/BookResource.java
> +     *
please return a dto

2022-11-21 14:18 UTC, garlontas commented on src/main/java/org/pickwicksoft/libraary/domain/Book.java
> +    public void addAuthor(Author author) {
Used in controller to add further authors to one book

2022-11-21 14:18 UTC, garlontas commented on src/main/java/org/pickwicksoft/libraary/domain/Book.java
> +    public void removeAuthor(long authorId) {
Same here

2022-11-21 14:21 UTC, garlontas commented on src/main/java/org/pickwicksoft/libraary/repository/AuthorRepository.java
> +public interface AuthorRepository extends JpaRepository<Author, Long> {
Does not work like that → it is automated

2022-11-28 19:02 UTC, garlontas commented on src/main/java/org/pickwicksoft/libraary/web/rest/AuthorResource.java
> +                var _author = authorRepository.save(authorRequest);
#28

2022-11-28 19:03 UTC, garlontas commented on src/main/java/org/pickwicksoft/libraary/web/rest/AuthorResource.java
> +    public ResponseEntity<Author> addAuthorToBook(@PathVariable Long bookId, @RequestBody Author authorRequest) {
Yes

2022-11-28 19:03 UTC, garlontas commented on src/main/java/org/pickwicksoft/libraary/web/rest/AuthorResource.java
> +    public ResponseEntity<HttpStatus> deleteAuthorFromBook(
Yes

2022-11-28 19:03 UTC, garlontas commented on src/main/java/org/pickwicksoft/libraary/web/rest/BookResource.java
> +     *
#28

2022-11-28 19:13 UTC, ngarlonta approved these changes

2022-11-29 18:05 UTC, merged